// src/data.ts
import { Customer, MileslinesProduct, ToshinService } from './types';

export const customerList: Customer[] = [
  { name: "英勤布業有限公司全興廠", address: "509004 彰化縣伸港鄉全興工業區工東一路41號", taxId: "23690554", phone: "(04) 797-8089" },
  { name: "翔逸貿易股份有限公司", address: "334019 桃園市八德區大興路110號14樓", taxId: "04243774", phone: "(03) 218-3944" },
  { name: "富郁有限公司", address: "330477 桃園市桃園區龜山工業區興隆路9號", taxId: "83641467", phone: "(03) 362-5231" },
  { name: "華城有限公司", address: "333024 桃園市龜山區海華路16巷8之1號", taxId: "43783502", phone: "(03) 350-7016" },
  { name: "新瑞倡企業股份有限公司", address: "333029 桃園市龜山區東舊路街100號", taxId: "07620770", phone: "(03) 329-8765" },
  { name: "紡邑豐實業有限公司", address: "338013 桃園市蘆竹區宏竹里大竹北路331巷53號", taxId: "84794659", phone: "(03) 313-2885" },
  { name: "紡裕豐股份有限公司", address: "338013 桃園市蘆竹區大竹北路331巷51號", taxId: "80013153", phone: "(03) 313-2885" },
  { name: "興邦印染廠股份有限公司", address: "236044 新北市土城區福安街114號", taxId: "33420382", phone: "(02) 2268-1290" },
  { name: "自行輸入", address: "", taxId: "", phone: "" }
];

export const mileslinesProducts: MileslinesProduct[] = [
  { description: '酒石酸', price: 0 },
  { description: '糊料 MAX8', price: 160 },
  { description: '豆糊 HS', price: 60 },
  { description: '糊料 3A', price: 120 },
  { description: '糊料 MY/12', price: 130 },
  { description: '糊料 TA/12', price: 130 },
  { description: '糊料 TA/8', price: 120 },
  { description: '糊料 EXBA', price: 150 },
  { description: '糊料 EX', price: 150 },
  { description: '印花油', price: 280 },
  { description: '印布油', price: 250 },
  { description: '糊料 PAN NEW', price: 90 },
  { description: '糊料 JOY/EXTRA', price: 70 },
  { description: '自行輸入', price: 0 }
];

export const toshinServices: ToshinService[] = [
  { category: "自動化控制", subCategory: "控制元件", item: "定位控制器", examples: ["SQC-5", "SQC-6", "SQC-T2"] },
  { category: "自動化控制", subCategory: "控制元件", item: "時序控制器", examples: ["UD-F70", "FX3G-24M", "NAiS KT4", "FRC100A-G02", "JAMSC-B2605", "JAMSC-C389", "JAMSC-B1090B"] },
  { category: "自動化控制", subCategory: "控制元件", item: "運算模組", examples: ["JAMSC-B2605", "JAMSC-C389", "JAMSC-B1090B"] },
  { category: "自動化控制", subCategory: "控制元件", item: "輸出/入模組", examples: ["Q01", "Q02U", "NC1P-EO", "DDSCR-U84S", "KZ-300", "KV-24AT", "FXIN-24MT"] },
  { category: "自動化控制", subCategory: "控制元件", item: "類比模組", examples: ["JAMSC-B2603", "JAMSC-B2605", "JAMSC-B2833", "KZ-C32X", "JAMSC-B2110A"] },
  { category: "自動化控制", subCategory: "控制元件", item: "通訊/網路模組", examples: ["Q64DAN", "JAMSC-B1054"] },
  { category: "自動化控制", subCategory: "控制元件", item: "電源模組", examples: ["JAMSC-C8610", "QJG1BT 11N CC-Link", "FX2N-32CCL"] },
  { category: "自動化控制", subCategory: "控制元件", item: "伺服馬達(Servopack)", examples: ["SGDH-XXXX", "SGDV-XXXX", "SD2A-XXXX"] },
  { category: "自動化控制", subCategory: "控制元件", item: "人機介面(HMI)", examples: ["GP-4301", "GP-2400", "GT-1150"] },
  { category: "自動化控制", subCategory: "控制元件", item: "操作開關與按鈕", examples: ["SB-2NB/21", "U-84S", "PUL-10A-10U"] },
  { category: "自動化控制", subCategory: "控制元件", item: "變頻器", examples: ["FVR", "CIMR", "VF-S9", "FVR3 7E9S-2TS", "FRN3.7C1S-2TS"] },
  { category: "自動化控制", subCategory: "控制元件", item: "繼電器、電磁接觸器", examples: ["HI-20EG"] },
  { category: "自動化控制", subCategory: "控制元件", item: "電纜線", examples: [] },
  { category: "自動化控制", subCategory: "控制元件", item: "端子台", examples: [] },  
  { category: "自動化控制", subCategory: "控制元件", item: "連接器", examples: [] },  
  { category: "自動化控制", subCategory: "感測元件", item: "近接開關", examples: [] },
  { category: "自動化控制", subCategory: "感測元件", item: "旋轉編碼器", examples: ["HES-01"] },
  { category: "自動化控制", subCategory: "感測元件", item: "測速發電機", examples: ["RP-112-AC", "RE-010-DC"] },
  { category: "自動化控制", subCategory: "感測元件", item: "光學感應器", examples: ["E2E-X8MD1"] },
  { category: "自動化控制", subCategory: "感測元件", item: "其他感測元件", examples: [] },  
  { category: "機械傳動", subCategory: "運動結構", item: "滑軌與滑動軸承", examples: ["Slide Shoe", "KRD065", "Sliding Sleeve", "Thrust Bearing"] },
  { category: "機械傳動", subCategory: "運動結構", item: "導輪與調整輪", examples: [] },
  { category: "機械傳動", subCategory: "運動結構", item: "印花皮帶", examples: ["Habasit"] },
  { category: "機械傳動", subCategory: "運動結構", item: "連桿、軸與軸承、齒輪：", examples: [] },
  { category: "機械傳動", subCategory: "運動結構", item: "電磁離合器、煞車蹄片", examples: [] },
  { category: "機械傳動", subCategory: "運動結構", item: "其他", examples: [] },
  { category: "機械傳動", subCategory: "運動輔助", item: "氣缸", examples: ["SY5120-5MU-C6-F2"] },
  { category: "機械傳動", subCategory: "運動輔助", item: "氣壓元件與管線", examples: [] }, 
  { category: "機械傳動", subCategory: "運動輔助", item: "油壓缸", examples: ["NCLFZ-15A", "PVB29-FR5-20-CMC-11-J", "PVB29-FRS-20-CMC-11-JA"] },
  { category: "機械傳動", subCategory: "運動輔助", item: "油壓濾芯", examples: [] },
  { category: "機械傳動", subCategory: "運動輔助", item: "油壓泵", examples: [] },
  { category: "機械傳動", subCategory: "運動輔助", item: "調整裝置", examples: [] },
  { category: "機械傳動", subCategory: "運動輔助", item: "刻度筒", examples: ["圓形刻度筒", "方型刻度筒"] },
  { category: "機械傳動", subCategory: "運動輔助", item: "其他", examples: ["7E9S-2TS"] },  
  { category: "耗材", subCategory: "耗材", item: "墨水", examples: ["FJ-600","SJ-540"] },
  { category: "耗材", subCategory: "耗材", item: "墨水噴頭", examples: [] },    
  { category: "耗材", subCategory: "耗材", item: "墨水管", examples: [] },  
  { category: "耗材", subCategory: "耗材", item: "聚酯網網布", examples: [] },
  { category: "耗材", subCategory: "耗材", item: "毛氈", examples: [] },
  { category: "耗材", subCategory: "耗材", item: "輸送帶網布", examples: [] },
  { category: "耗材", subCategory: "耗材", item: "橡膠刮刀", examples: [] },
  { category: "耗材", subCategory: "耗材", item: "清潔棒", examples: [] },  
  { category: "耗材", subCategory: "耗材", item: "碳刷", examples: [] },
  { category: "耗材", subCategory: "耗材", item: "油封", examples: [] },
  { category: "耗材", subCategory: "耗材", item: "橡膠板", examples: [] }, 
  { category: "特殊項目", description: '運費', priceJPY: 0 },
  { category: "特殊項目", description: '自行輸入', priceJPY: 0 }
];